name: code review

on:
  pull_request:
    branches: "main"

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Checkstyle
      uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: google_checks.xml
          level: warning
